<?php
namespace backend\models;

use yii\helpers\ArrayHelper;

class Articulo extends \common\models\Articulo
{
    public function fields()
    {
        return ArrayHelper::merge(parent::fields(),['tela','url']); // TODO: Change the autogenerated stub
    }

    public function getUrl($width = 60, $height = 60)
    {
        return parent::getUrl($width, $height); // TODO: Change the autogenerated stub
    }

}
